# Generated by Django 3.0.3 on 2020-02-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_productcustomfield_snipcartsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
