# Generated by Django 3.0.5 on 2020-04-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_desc',
            new_name='short_description',
        ),
    ]
